gui:
  showRandomTip: false
  showCommandLog: false
git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --paging=never --dark --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"


promptToReturnFromSubprocess: false
