gui:
  showRandomTip: false
  showCommandLog: false
os:
  edit: 'nvim'
git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

promptToReturnFromSubprocess: false

theme:
  lightTheme: false
  activeBorderColor:
    - "#a6d189" # Green
    - bold
  inactiveBorderColor:
    - "#c6d0f5" # Text
  optionsTextColor:
    - "#8caaee" # Blue
  selectedLineBgColor:
    - "#414559" # Surface0
  selectedRangeBgColor:
    - "#414559" # Surface0
  cherryPickedCommitBgColor:
    - "#81c8be" # Teal
  cherryPickedCommitFgColor:
    - "#8caaee" # Blue
  unstagedChangesColor:
    - red       # Red
