#!/bin/bash
echo "Running $0 $1 $2" >> /tmp/nm-dispatcher.log
wired_interfaces="^en.*|^eth.*"
if [[ "$1" =~ $wired_interfaces ]]; then
    case "$2" in
        up)
            nmcli radio wifi off
            ;;
        down)
            nmcli radio wifi on
            ;;
    esac
fi
