import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]
[window]
decorations = "Full"
opacity = 0.8
blur = true
padding.x = 3
padding.y = 3
option_as_alt = "Both"

[font]

normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

size = 16.0
