import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[window]
decorations = "Full"
opacity = 0.9
blur = true
padding.x = 3
padding.y = 3
option_as_alt = "Both"

[selection]
save_to_clipboard = true

[font]
normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"
use_thin_strokes = true
size = 18.0

[mouse]
hide_when_typing = false

[scrolling]
history = 100000
